url: http://nickhowson.id.au
# baseurl: /

# Site Settings
title: "Nick Howson"
description: "null"
keywords: "jekyll, timeline, portfolio"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown", "start_devserver.bat"]
